name: Release (callable)

on:
  workflow_call:
    inputs:
      publish:
        description: If true, run the publishing step
        required: false
        default: true
        type: boolean
      publish-npm:
        description: If true, publish to npm registry via `npm publish`. If false, run `npm run publish` instead.
        required: false
        default: true
        type: boolean
      node-version:
        description: Node.js version
        required: false
        default: 'lts/*'
        type: string
    secrets:
      # NOTE: If publishing via OIDC is available, this secret may not be required.
      # Ref https://github.com/microsoft/vscode-vsce/issues/1133
      VSCE_PAT:
        description: Personal Access Token for publishing to Visual Studio Marketplace
        required: false

jobs:
  release:
    # Only when a PR with a branch name starting with `release/` is merged.
    # For the branch name convention, see `call-release-pr.yml`.
    if: |
      github.event.pull_request.merged == true &&
      startsWith(github.event.pull_request.head.ref, 'release/')

    runs-on: ubuntu-latest

    permissions:
      contents: write
      id-token: write # Required for OIDC. See https://docs.npmjs.com/trusted-publishers

    timeout-minutes: 10

    # Require manual approval before publishing.
    # See https://docs.github.com/en/actions/how-tos/deploy/configure-and-manage-deployments/control-deployments
    environment: npm
    concurrency: npm

    defaults:
      run:
        shell: bash

    steps:
      - name: Checkout
        uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1

      - name: Get version
        id: get-version
        env:
          PR_HEAD_BRANCH: ${{ github.event.pull_request.head.ref }}
        run: |
          # Check if the package version matches the branch name
          PKG_VERSION=$(jq -r '.version' package.json)
          if [[ "${PR_HEAD_BRANCH}" == "release/${PKG_VERSION}" ]]; then
            echo "version=${PKG_VERSION}" >> "${GITHUB_OUTPUT}"
          else
            echo "::error::The version '${PKG_VERSION}' in package.json does not match the version in the branch name '${PR_HEAD_BRANCH}'."
            exit 1
          fi

      - name: Set up Node.js ${{ inputs.node-version }}
        uses: actions/setup-node@395ad3262231945c25e8478fd5baf05154b1d79f # v6.1.0
        with:
          node-version: ${{ inputs.node-version }}
          registry-url: 'https://registry.npmjs.org'
          cache: npm

      - name: Install latest npm
        run: npm install --global npm@latest

      - name: Install dependencies
        run: npm ci

      - name: Publish to npm registry
        if: ${{ inputs.publish && inputs.publish-npm }}
        run: |
          npm publish
          package_name=$(jq -r '.name' package.json)
          package_version=$(jq -r '.version' package.json)
          echo "::notice::Published https://www.npmjs.com/package/${package_name}/v/${package_version}"

      - name: Run non-npm publishing
        if: ${{ inputs.publish && !inputs.publish-npm }}
        run: npm run publish
        env:
          VSCE_PAT: ${{ secrets.VSCE_PAT }}

      - name: Create GitHub release
        uses: stylelint/changelog-to-github-release-action@027dd126c5e8e27e2d7f436872be1f4d0663c347 # 0.5.2
        with:
          tag: ${{ steps.get-version.outputs.version }}
          draft: true
