name: Release (callable)

on:
  workflow_call:
    inputs:
      publish:
        description: Set true if publishing to npm registry
        required: false
        default: true
        type: boolean
      node-version:
        description: Node.js version
        required: false
        default: 'lts/*'
        type: string

jobs:
  release:
    # Only when a PR with a branch name starting with `release/` is merged.
    # For the branch name convention, see `call-release-pr.yml`.
    if: |
      github.event.pull_request.merged == true &&
      startsWith(github.event.pull_request.head.ref, 'release/')

    runs-on: ubuntu-latest

    permissions:
      contents: write
      id-token: write # Required for OIDC. See https://docs.npmjs.com/trusted-publishers

    timeout-minutes: 10

    # Require manual approval before publishing.
    # See https://docs.github.com/en/actions/how-tos/deploy/configure-and-manage-deployments/control-deployments
    environment: npm
    concurrency: npm

    defaults:
      run:
        shell: bash

    steps:
      - name: Checkout
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0

      - name: Get version
        id: get-version
        env:
          PR_HEAD_BRANCH: ${{ github.event.pull_request.head.ref }}
        run: |
          # Check if the package version matches the branch name
          PKG_VERSION=$(jq -r '.version' package.json)
          if [[ "${PR_HEAD_BRANCH}" == "release/${PKG_VERSION}" ]]; then
            echo "version=${PKG_VERSION}" >> "${GITHUB_OUTPUT}"
          else
            echo "::error::The version '${PKG_VERSION}' in package.json does not match the version in the branch name '${PR_HEAD_BRANCH}'."
            exit 1
          fi

      - name: Set up Node.js ${{ inputs.node-version }}
        uses: actions/setup-node@2028fbc5c25fe9cf00d9f06a71cc4710d4507903 # v6.0.0
        with:
          node-version: ${{ inputs.node-version }}
          registry-url: 'https://registry.npmjs.org'

      - name: Install latest npm
        run: npm install --global npm@latest

      - name: Install dependencies
        run: npm ci

      - name: Publish to npm registry
        if: ${{ inputs.publish }}
        run: |
          npm publish
          package_name=$(jq -r '.name' package.json)
          echo "::notice::Published https://www.npmjs.com/package/${package_name}"

      - name: Create GitHub release
        uses: stylelint/changelog-to-github-release-action@8526eab6046b8f5b2f883844d953b5eb6f80e674 # 0.5.1
        with:
          tag: ${{ steps.get-version.outputs.version }}
          draft: true
